### PR TITLE
Changing folder structure to match with containers and components

### PR DESCRIPTION
**Pull request by eduardomoroni**
image
image

For reference:
https://medium.com/@learnreact/container-components-c0e67432e005
https://github.com/reactjs/redux/issues/756

### CODE REVIEW

**Comment by eduardomoroni** [comment]
@Aprendfy/dev-team

**Comment by eduardomoroni** [comment]
Os 30 novos issues do codeclimate, na verdade são os mesmo 30 que já existiam.

**Comment by eduardomoroni** [comment]
Encontrei uns erros, não mergeem.

**Review by hebertporto — APPROVED** [review]
Reviwed

**Pull request merged**
